### ISSUE TITLE
MySQL issues

### ISSUE THREAD

**Issue by Caaine** [Arkarr/-ANY-Contract#6]
Hey Arkarr

I have

databases.cfg:

"store"
{
	"driver"			"default"
	"host"				"localhost"
	"database"			"XxxXXx"
	"user"				"XxxxX"
	"pass"				"xXXxxxXXx"
	//"timeout"			"0"
	"port"				"xxxx"
}

Server.cfg;

sm_database_configuration_name "store"
sm_contract_store_select "ZEPHYRUS"

The table is not created what is wrong?

greetz
Caaine

**Comment by Arkarr** [comment]
I don't know. Any error logs ?

**Comment by Caaine** [comment]
no error logs... sry :(

greetz
caaine

**Comment by Arkarr** [comment]
Are you sure ? Normally it should pop-up something. Check again.

**Comment by Caaine** [comment]
L 08/21/2017 - 14:17:00: SourceMod error session started
L 08/21/2017 - 14:17:00: Info (map "jb_snow_v2") (file "errors_20170821.log")
L 08/21/2017 - 14:17:00: [store.smx] Gifts! isn't installed or failed to load. Gifts support will be disabled. Please install Gifts. (http://forums.alliedmods.net/showthread.php?t=175185)
L 08/21/2017 - 14:17:13: Error log file session closed.

no sry its the last error log :(

**Comment by Arkarr** [comment]
try **sm plugins load "[ANY] Contract"**

**Comment by Caaine** [comment]
http://i.imgur.com/Rq0Q651.png
http://i.imgur.com/wX1cL5P.png

**Comment by Arkarr** [comment]
try **sm plugins reload "[ANY] Contract"**

**Comment by Caaine** [comment]
nothing

http://i.imgur.com/RyLKR3q.png
http://i.imgur.com/6Ss4tT9.png

**Comment by Arkarr** [comment]
No idea. I'll do test on my own.

**Comment by Caaine** [comment]
Done with the Test? :D

**Comment by Arkarr** [comment]
Nah.

**Comment by Arkarr** [comment]
Looks like it's a problem with your database host / id.
I can run the plugin just fine.
Can't you check the logs from the database server you have ?

**Comment by Caaine** [comment]
no logs from mysql and GameServer

**Comment by Arkarr** [comment]
Do you mind if I set it up for you on your server ? I would need the logins. Something ain't right.

**Comment by Caaine** [comment]
nvm reinstall system and mysql

working now
